/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author m
 */
public class DesafioGenio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DesafioGenio.class.getName());

    /**
     * Creates new form DesafioGenio
     */
    public DesafioGenio() {
        initComponents();
        lblMensagem.setText("<html>Vou pensar em um valor<br>entre 1 e 5.<br>Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnNumero = new javax.swing.JSpinner();
        btnVerificar = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Palpite:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        spnNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(this::btnVerificarActionPerformed);
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/image/Gênio.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/image/balão-de-fala-200.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        
        // Gera um número aleatório entre 1 e 5
        // Math.random() gera um número decimal entre 0.0 e 0.999...
        // Multiplicando por 5 → fica entre 0.0 e 4.999...
        // (int) corta a parte decimal → vira 0 a 4
        // +1 ajusta o intervalo → agora fica de 1 a 5
        int numeroSistema = (int)(Math.random() * 5) + 1;
        
        //Pega o valor escolhido pelo usuario no spinner
        int numeroUsuario = (int) spnNumero.getValue();

        if (numeroUsuario == numeroSistema) { // Se o numero escolhido for igual ao gerado pelo sistema
           // <html> ativa formatação no JLabel → permite usar <br> (quebra linha) e <center> para centralizar o texto
           //Se for igual, mostra que acertou
            lblMensagem.setText("<html><center>ACERTOU!</center></html>");
        } else {
            //Mostra que errou e qual era o número correto
            lblMensagem.setText("<html><center>ERROU!<br>Estava pensando no número " + numeroSistema + "</center></html>");
        }

        // javax.swing.Timer é uma classe do Swing usada para executar algo depois de um tempo; timer é o objeto
        javax.swing.Timer timer = new javax.swing.Timer(3000, e -> {
            lblMensagem.setText("<html><center>Vou pensar em um valor<br>entre 1 e 5.<br>Tente adivinhar!</center></html>");
        });

        timer.setRepeats(false); // executa só uma vez
        timer.start();// Inicia o Timer
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DesafioGenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JSpinner spnNumero;
    // End of variables declaration//GEN-END:variables
}
